Repository usd-cs/comp495-sp18-travely, pull requests merged in 2018-04, with the labels that each got.

#100 added UI elements to about tab for currency calculator
  travely.xcodeproj/project.pbxproj
  travely/AboutViewController.swift
  travely/Base.lproj/Main.storyboard
Labels: enhancement

#116 Persist take dos
  travely/MyTripsTableViewController.swift
  travely/NewTripViewController.swift
  travely/Trip.swift
Labels: bug

#119 fixed about bugs
  travely/AboutViewController.swift
  travely/CostViewController.swift
Labels: bug

#142 Refined code
  travely.xcodeproj/project.pbxproj
  travely/ActivitiesTabTableViewController.swift
  travely/ActivitiesViewController.swift
  travely/ActivityDetailsViewController.swift
  travely/LoadingScreenViewController.swift
  travely/Models/Activities.swift
  travely/Models/Airfairs.swift
  travely/Models/Country.swift
  travely/Models/Hotels.swift
  travely/Models/Trip.swift
  travely/NewTripViewController.swift
  travely/SavedTripDetailsViewController.swift
  travely/countryEtiquette.txt
Labels: help wanted

#147 Fixed Update Activities Table
  travely/ActivitiesTabTableViewController.swift
  travely/Models/Activities.swift
  travely/Models/Country.swift
Labels: bug

#141 added email trip implementation. Body Message is missing but its all …
  travely/Base.lproj/Main.storyboard
  travely/SavedTripDetailsViewController.swift
Labels: enhancement

#151 Emailing take 2
  travely/Base.lproj/Main.storyboard
  travely/SavedTripDetailsViewController.swift
Labels: enhancement

#156 added contents to the body
  travely/MyTripsTableViewController.swift
  travely/SavedTripDetailsViewController.swift
Labels: enhancement

#169 fixed code warnings, we still have some constraints warning so i'll b…
  travely/ActivitiesTabTableViewController.swift
  travely/Base.lproj/Main.storyboard
  travely/NewTripViewController.swift
Labels: good first issue

#190 activities are added to report and email
  travely/ActivitiesTabTableViewController.swift
  travely/Base.lproj/Main.storyboard
  travely/LoadingScreenViewController.swift
  travely/Models/Activities.swift
  travely/Models/Activity.swift
  travely/Models/Trip.swift
  travely/MyTripsTableViewController.swift
  travely/NewTripViewController.swift
  travely/SavedTripDetailsViewController.swift
Labels: enhancement

#193 added hotel change with num of travelers
  travely/CostViewController.swift
Labels: bug
